tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#4c4546",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-container": "#83838c",
        "on-surface": "#1a1c1d",
        "outline-variant": "#cfc4c5",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-container": "#616363",
        "on-error-container": "#93000a",
        "surface-variant": "#e2e2e3",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed-variant": "#454747",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e3",
        "on-tertiary-fixed-variant": "#46464e",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1a1c1c",
        "surface-dim": "#dadadb",
        "surface-container-low": "#f3f3f4",
        "inverse-primary": "#c6c6c6",
        "on-primary-container": "#848484",
        "on-primary-fixed-variant": "#474747",
        "on-background": "#1a1c1d",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "tertiary": "#000000",
        "outline": "#7e7576",
        "on-tertiary-fixed": "#1a1b22",
        "surface-container": "#eeeeef",
        "surface-bright": "#f9f9fa",
        "surface": "#f9f9fa",
        "tertiary-fixed": "#e3e1ec",
        "secondary-container": "#dfe0e0",
        "background": "#f9f9fa",
        "secondary-fixed-dim": "#c6c6c7",
        "primary": "#000000",
        "tertiary-container": "#1a1b22",
        "tertiary-fixed-dim": "#c6c5cf",
        "surface-container-high": "#e8e8e9",
        "secondary": "#5d5f5f",
        "inverse-on-surface": "#f0f1f2",
        "inverse-surface": "#2f3132",
        "primary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
};
